# Generated by Django 3.0.6 on 2020-06-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
