# Generated by Django 3.0.6 on 2020-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descrption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
