# Generated by Django 3.0.6 on 2020-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_descrption'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exprience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacany',
            field=models.IntegerField(default=1),
        ),
    ]
